---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    haproxy.org/cookie-persistence: "mycookie"
spec:
  selector:
    run: app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80