apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
    version: '1.3'
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
      version: '1.3'
  template:
    metadata:
      labels:
        run: app
        version: '1.3'
    spec:
      containers:
      - name: app
        image: quay.io/nickmramirez/webapp:1.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["PID=`pidof node`", "kill -SIGTERM $PID"]
